name: CI

on: [push]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install packages
        run: pnpm install
      - name: Lint source code ESLint
        run: pnpm lint

  test:
    name: Jest
    runs-on: ubuntu-letest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
          with:
            version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install packages
        run: pnpm install
      - name: Unit-test
        run: pnpm test

  build:
    name: Build
    runs-on: ubuntu-letest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
          with:
            version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install packages
        run: pnpm install
      - name: Build web-app
        run: pnpm build

  screenshots-test:
    name: Screenshots test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
          with:
            version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install packages
        run: pnpm ci
      - name: Build Storybook
        run: pnpm storybook:build
      - name: Run loki test
        run: pnpm loki:ci
