name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-lastes
    steps:
      - uses: actions/checkout@v3
      - name: Instal NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - name: Instal Node
        env:
          NODE_VERSION: 16.15.1
        run: nvm install $NODE_VERSION
      - name: Instal dependencies
        run: npm ci
      - name: lint code on ESLint
        run: npm run lint