name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    container:
      image: node:16.15.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Instal dependencies
        run: npm ci
      - name: lint code on ESLint
        run: npm run lint