name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:16.15.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Instal dependencies
        run: npm ci
      - name: Lint code on ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    container:
      image: node:16.15.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Instal dependencies
        run: npm ci
      - name: Test code
        run: npm run test